routes/auth_routes.py
from flask import Blueprint, render_template, redirect, url_for, request, flash
from flask_login import login_user, logout_user, login_required, current_user
from models.user import User
import bcrypt
auth_bp = Blueprint('auth', __name__)

@auth_bp.route('/login', methods=['GET', 'POST'])
def login():
    if request.method == 'POST':
        email = request.form['email']
        password = request.form['password']
        print(bcrypt.hashpw(password.encode('utf-8'), bcrypt.gensalt()).decode('utf-8'))
        user = User.validate_password(email, password)
        print(user)
        if user:
            login_user(user)
            return redirect(url_for('home.index'))
        else:
            flash('Invalid credentials','danger')
    return render_template('login.html')

@auth_bp.route('/logout')
@login_required
def logout():
    logout_user()
    return redirect(url_for('auth.login'))

@auth_bp.route('/signup', methods=['GET', 'POST'])
def signup():
    logout_user()
    if request.method == 'POST':
        fullname = request.form['fullname']
        email = request.form['email']
        password = request.form['password']
        user = User.create(fullname,email, password)
        if user:
            flash('User registered successfully', 'success')
            return redirect(url_for('auth.login'))
        else:
            flash('User already exists','danger')
    return render_template('signup.html')

@auth_bp.route('/update-password', methods=['POST'])
@login_required
def update_password():
    if request.method == 'POST':
        email = current_user.email
        print(email)
        new_password = request.form['new_password']
        user = User.update_password(email, new_password)
        if user:
            flash('Password updated successfully','success')
        else:
            flash('User does not exist','danger')
    return render_template('update_password.html')

@auth_bp.route('/delete-account/<email>')
@login_required
def delete_account(email):
    if User.delete(email):
        flash('Account deleted successfully','success')
    else:
        flash('User does not exist','danger')
    return redirect(url_for('home.management'))

@auth_bp.route('/dashboard')
@login_required
def dashboard():
    user_role = User.get_role(current_user.id)
    return render_template('dashboard.html', role=user_role)

templates/delete_account.html
<form method="POST" action="{{ url_for('auth.delete_account') }}">
    <label for="email">Email</label>
    <input type="text" name="email" id="email" required>

    <button type="submit">Delete Account</button>
</form>

templates/homepage.html
{% extends "index.html" %}
{% block title %}Home Page{% endblock %}
{%block content%}
<div class="card shadow mt-3" >
   <div class="row justify-content-center">
    <div class="col-sm-3">
        <img style="width: 200px;" src="/static/ayam.png" alt="">
    </div>
    <div class="col-sm-9 mt-3">
        <div style="font-size: 28px; font-family:'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;">
            <strong class="text-dark"><p>
                Halo <span id="namaUser">Admin!</span> <br>
                Hindari Ayam Formalin <br>
                Pilih yang Sehat dan Aman!
            </p></strong>
        </div>
    </div>
   </div>
</div>

{%endblock%}

templates/login.html
{% extends "index.html" %}
{% block title %}Testing Page{% endblock %}
{%block content%}

<div class="container">
    <!-- Outer Row -->
    <div class="row justify-content-center">

        <div class="col-xl-6 col-lg-6 col-md-9">

            <div class="card o-hidden border-0 shadow-lg my-5">
                <div class="card-body p-0">
                    <!-- Nested Row within Card Body -->
                    <div class="row">
                        <div class="col-lg">
                            <div class="p-5">
                                <div class="text-center">
                                    <h1 class="h4 text-gray-900 mb-4">Welcome Back!</h1>
                                </div>
                                {% with messages = get_flashed_messages(with_categories=True) %}
                                {% if messages %}
                                {% for category, message in messages %}
                                <div id="resultCard" class="alert alert-{{ category }} p-2">
                                    {{ message }}
                                </div>
                                {% endfor %}
                                {% endif %}
                                {% endwith %}
                                <form class="user" method="POST" action="{{ url_for('auth.login') }}">
                                    <div class="form-group">
                                        <input type="email" name="email" class="form-control form-control-user"
                                            id="exampleInputEmail" aria-describedby="emailHelp"
                                            placeholder="Enter Email Address...">
                                    </div>
                                    <div class="form-group">
                                        <input type="password" name="password" class="form-control form-control-user"
                                            id="exampleInputPassword" placeholder="Password">
                                    </div>

                                    <button class="btn btn-primary btn-user btn-block" type="submit">Login</button>
                                    <hr>
                                </form>

                                <div class="text-center">
                                    <a class="small" href="{{ url_for('auth.signup')}}">Create an Account!</a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

        </div>

    </div>

</div>

{%endblock%}

templates/management_user.html
{% extends "index.html" %}
{% block title %}Management User{% endblock %}
{%block content%}
<div class="card shadow mt-3 p-3">
    {% with messages = get_flashed_messages(with_categories=True) %}
    {% if messages %}
    {% for category, message in messages %}
    <div id="resultCard" class="alert alert-{{ category }} p-2">
        {{ message }}
    </div>
    {% endfor %}
    {% endif %}
    {% endwith %}
    <div class="row justify-content-center">
        <div class="col mt-3">
            <table class="table">
                <thead>
                    <th>No</th>
                    <th>Nama Lengkap</th>
                    <th>Email</th>
                    <th>Akses</th>
                    <th>Aksi</th>
                </thead>
                <tbody class="table-body">
                    {% for user in users %}
                    <tr>
                        <td>{{ loop.index }}</td>
                        <td>{{ user.fullname }}</td>
                        <td>{{ user.email }}</td>
                        <td>{{ user.role }}</td>
                        <td>
                            <a href="/delete-account/{{user.email}}" class="btn btn-sm btn-danger btn-icon-split"
                                onclick="return confirmDelete()">
                                <span class="icon text-white">
                                    <i class="fas fa-trash"></i>
                                </span>
                            </a>

                            <script>
                                function confirmDelete() {
                                    return confirm("Apakah kamu yakin ingin menghapus data ini ?");
                                }
                            </script>

                        </td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</div>

{%endblock%}

templates/signup.html
{% extends "index.html" %}
{% block title %}Testing Page{% endblock %}
{%block content%}


<div class="container">
    <!-- Outer Row -->
    <div class="row justify-content-center">

        <div class="col-xl-6 col-lg-6 col-md-9">

            <div class="card o-hidden border-0 shadow-lg my-5">
                <div class="card-body p-0">
                    <!-- Nested Row within Card Body -->
                    <div class="row">
                        <div class="col-lg">
                            <div class="p-5">
                                <div class="text-center">
                                    <h1 class="h4 text-gray-900 mb-4">Welcome Back!</h1>
                                </div>
                                {% with messages = get_flashed_messages(with_categories=True) %}
                                {% if messages %}
                                {% for category, message in messages %}
                                <div id="resultCard" class="alert alert-{{ category }} p-2">
                                    {{ message }}
                                </div>
                                {% endfor %}
                                {% endif %}
                                {% endwith %}
                                <form class="user" method="POST" action="{{ url_for('auth.signup') }}">
                                    <div class="form-group">
                                        <input type="text" name="fullname" class="form-control form-control-user" placeholder="Fullname...">
                                    </div>
                                    <div class="form-group">
                                        <input type="email" name="email" class="form-control form-control-user"
                                            id="exampleInputEmail" aria-describedby="emailHelp"
                                            placeholder="Enter Email Address...">
                                    </div>
                                    <div class="form-group">
                                        <input type="password" name="password" class="form-control form-control-user"
                                            id="exampleInputPassword" placeholder="Password">
                                    </div>

                                    <button class="btn btn-primary btn-user btn-block" type="submit">Register</button>
                                    <hr>
                                </form>

                                <div class="text-center">
                                    <a class="small" href="{{ url_for('auth.login')}}">Log In</a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

        </div>

    </div>

</div>
{%endblock%}

templates/testing.html
{% extends "index.html" %}
{% block title %}Testing Page{% endblock %}
{%block content%}

<form id="identificationForm" method="POST" enctype="multipart/form-data">
    <div class="row mt-3">
        <div class="col-sm-6 mb-3 mb-sm-0">
            <div class="card shadow mb-4">
                <img id="previewImage" style="height: 360px; object-fit: cover; margin: 10px;"
                    src="{{ url_for('static', filename='no-image.jpg') }}" class="border rounded"
                    alt="Gambar Tidak Muncul">
                <div class="card-body">
                    <h5 class="card-title">Upload Foto Daging Ayam</h5>
                    <p class="card-text">Upload foto daging ayam untuk melakukan testing.</p>
                    <input id="fileInput" style="max-width: 300px;" class="form-control" name="test_file" type="file"
                        multiple> <br>
                    <button type="button" id="extract-button" class="btn btn-primary adminOnly">Ekstrak Ciri</button>
                    <div class="adminOnly">
                        <div class="mb-3 mt-3">
                            <label for="">Input K Value</label>
                            <div class="row">
                                <div class="col-3">
                                    <input class="form-control" type="number" name="k_value" min="1" value="{{k_value}}" id="knn-value">

                                </div>
                                <div class="col">
                                    <button type="button" id="save-knn"
                                        class="btn btn-primary adminOnly">Simpan</button>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

            </div>
        </div>
        <div class="col-sm-6">
            <div class="card shadow mb-4">
                <img id="processed-image" style="height: 360px; object-fit: cover; margin: 10px;"
                    src="{{ url_for('static', filename='no-image.jpg') }}" class="object-fit-cover border rounded"
                    alt="Gambar Tidak Muncul">
                <div class="card-body">
                    <h5 class="card-title">Citra HSV</h5>
                    <table class="table">
                        <thead>
                            <th>No</th>
                            <th>Ciri</th>
                            <th>Nilai</th>
                        </thead>
                        <tbody id="feature-table-body">
                            <!-- Data akan diisi oleh jQuery -->
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>

    <div class="card shadow">
        <button type="button" id="identifyBtn" class="btn btn-success m-2 adminOnly">Identifikasi</button>
        <div id="resultCard" class="card m-2 py-3 border-bottom-secondary">
            <div class="card-body" id="resultText" style="text-align: center; font-size: 24px; font-weight: bold;">
            </div>
        </div>
    </div>
    <a href="" class="btn btn-danger mt-3">Reset</a>
</form>


{% if result %}
<h2>Prediction Result: {{ result }}</h2>
{% endif %}
{%endblock%}

templates/training.html
{% extends "index.html" %}
{% block title %}Training Page{% endblock %}
{%block content%}


<div class=" mt-3">
    <form id="trainingForm" method="POST" enctype="multipart/form-data">
        <div class="row">
            <div class="col-sm-6 mb-3 mb-sm-0">
                <div class="card">
                    <div id="previewContainerFormalin">
                        <!-- Preview images will be inserted here -->
                        <img id="defaultImageFormalin" style="height: 360px; object-fit: cover; margin: 10px;"
                            src="{{ url_for('static', filename='no-image.jpg') }}" class="border rounded"
                            alt="Gambar Tidak Muncul">
                    </div>
                    <div class="card-body">
                        <h5 class="card-title">Sample Formalin</h5>
                        <p class="card-text">Upload sample foto daging ayam yang menggunakan formalin.</p>
                        <input style="max-width: 300px;" class="form-control" name="formalin_files" type="file"
                            id="formalinImageInput" multiple>
                    </div>
                </div>
            </div>
            <div class="col-sm-6">
                <div class="card">
                    <div id="previewContainerNonFormalin">
                        <!-- Preview images will be inserted here -->
                        <img id="defaultImageNonFormalin" style="height: 360px; object-fit: cover; margin: 10px;"
                            src="{{ url_for('static', filename='no-image.jpg') }}" class="border rounded"
                            alt="Gambar Tidak Muncul">
                    </div>
                    <div class="card-body">
                        <h5 class="card-title">Sample Tidak Formalin</h5>
                        <p class="card-text">Upload sample foto daging ayam yang tidak menggunakan formalin.</p>
                        <input style="max-width: 300px;" class="form-control" name="non_formalin_files" type="file" 
                        id="nonFormalinImageInput" multiple>
                    </div>
                </div>
            </div>
        </div>
        <div id="progressContainer" style="display: none;">
            <div class="progress mt-3">
                <div id="progressBar" class="progress-bar" role="progressbar" style="width: 0%;" aria-valuenow="0"
                    aria-valuemin="0" aria-valuemax="100">0%</div>
            </div>
        </div>
        <button id="trainBtn" style="width: 100%;" class="btn btn-primary mt-3" type="submit">Training</button>
    </form>
</div>

{%endblock%}

templates/update_password.html
{% extends "index.html" %}
{% block title %}Setting{% endblock %}
{%block content%}
<div class="card shadow mt-3 p-3">
    <div class="row justify-content-center">
        <div class="col-6">
            <form class="user" method="POST" action="{{ url_for('auth.update_password') }}">
                <div class="row">
                    <div class="col">
                        {% with messages = get_flashed_messages(with_categories=True) %}
                        {% if messages %}
                        {% for category, message in messages %}
                        <div id="resultCard" class="alert alert-{{ category }} p-2">
                            {{ message }}
                        </div>
                        {% endfor %}
                        {% endif %}
                        {% endwith %}
                        <!-- <div class="form-group">
                            <input type="password" name="current_password" class="form-control form-control-user"
                                id="exampleInputPassword" placeholder="Password saat ini">
                        </div> -->
                        <div class="form-group">
                            <input type="password" name="new_password" class="form-control form-control-user"
                                id="exampleInputPassword" placeholder="Password baru">
                        </div>
                        <button class="btn btn-primary btn-user btn-block" type="submit">Ubah Passsword</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>

{%endblock%}